### ISSUE TITLE
App Idea #1: Automatic Notifications from Amazon and eBay

### ISSUE THREAD

**Issue by KairuRengu** [KairuRengu/iPhone-Application#1]
This will automatically make a notification to the user whenever the user receives an email with a date. This way the user will be reminded that a package is supposed to come without having to manually set up the reminder themselves. Plans for eBay and Amazon. Future plans to allow for any online delivery to work, also near field communications for things like laundry.

**Comment by hilts-vaughan** [comment]
Closing; we have decided.
