### ISSUE TITLE
Do iPhones use a different email service than gmail?

### ISSUE THREAD

**Issue by KairuRengu** [KairuRengu/iPhone-Application#2]
I don't know if they do, but it might be useful to know if they do. If they do we may want to focus that we are only going to do use gmail because it might be too much of work to do all email services.

Also useful link to the gmail api for swift:https://developers.google.com/gmail/api/quickstart/ios?ver=swift

**Comment by hilts-vaughan** [comment]
The scanning probably can't be done on the device. There probably needs to
be a cloud service that reads the mail and then pushes the summary of the
TODO to a database, in which the app can then read.

**Comment by KairuRengu** [comment]
We would need to still authenticate the user, using their own email addresses would we not? The main reason its asked because to access their emails we need to authenticate with their email service.

**Comment by hilts-vaughan** [comment]
Yes, but mail operates over a standard protocol.. so all mail servers can
communicate with each other. :)

**Comment by KairuRengu** [comment]
Fair eough

**Comment by hilts-vaughan** [comment]
Closed; we know the answer to this.
