### ISSUE TITLE
App Idea #2: What should I make for Dinner

### ISSUE THREAD

**Issue by KairuRengu** [KairuRengu/iPhone-Application#3]
Maybe we can have something that searches all recipes online and recommend recipes to you. We can also make it so that it will have a list of inventory that you have in your house and then pull those recipes and says which ones you can make.

**Comment by KairuRengu** [comment]
Example, say we have lemon, chicken, and lettuce, and tomatoes you can make a lemon flavoured chicken and salad

**Comment by hilts-vaughan** [comment]
Unfortunately, there's 100s of these ready to download. What's different
here?

**Comment by hilts-vaughan** [comment]
Decided on something else.
